<!DOCTYPE html>
<html>
	<?php @session_start()?>
	<title>Affordance app test</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	
	<style>
	body{
		background-color: #9999ff;
		font-family:  Arial, Helvetica, sans-serif;
	}
	#wrapper{
		margin-left: 2%;
		margin-right:2%;
		margin-top: 1%;
		margin-bottom: 1%;
		padding:0.5% 2% 2% 2%;
		background-color: #efefff;
		box-shadow: 5px 5px 10px #555588;
		border-radius: 25px;
	}

	#aff {
		width: auto;
		text-align: center
		margin-right :3%
	}
	
	.highlight{
		background-color: yellow;
	}
	.sentence{
		border : solid 5px #000077;
		padding : 15px;
		margin-top : 3px;
		background-color: #FFFFFF;
		border-radius: 25px;
	}
	
	.review{
		font-size: 130%;
	}
	.text{
		margin-right: 10px;
		float: none;vertical-align: middle;
	}
	
	.text-grey{
		margin-right: 10px;
		background-color: #dddddd;
		float: none;vertical-align: middle;
	}
	#title{
		background-color: #8888dd;
		color : white;
		padding: 30px;
		border-radius: 25px;
		
	}
	
	#instructions{
		background-color: #8888dd;
		color : white;
		padding: 10px;
		margin-top : 20px;
		border-radius: 25px;
		padding-left: 30px;
	}	
	
	.bar-border{
		border: solid 5px #000077;
		background-color: #eaeaea;
		height: 50px;
		width: 80%;
		float: right;
		border-radius: 25px;
		overflow: hidden;

		
	}
	
	.bar-fill{
		background-color:#8888dd;
		height: 100%;
		text-align: center;
		font-weight:bold;
		font-size: 150%;
		line-height: 50px;
		color : #ffffff;
	}
	
	.progress{
		float:right;
		text-align: center;
		font-weight:bold;
		font-size: 150%;
		line-height: 55px;
		margin-right: 10px
	}
	
	input{
		border-radius: 10px;
		font-size: 120%;
		background-color: #eeeeef;
		padding: 5px;
		
	}
	input:hover{
		box-shadow: 0 0 5px 3px #aaaaff;
	}
	
	</style>


	<body>
	<div id = "wrapper">
		<h1 id = "title">Affordance annotation</h1>
		<h4><?php 
			if(!isset($_SESSION['name'])){
				header("Location: login.php");
			}
			//echo "Welcome ". $_SESSION["name"]; ?></h4>
		<h2 style= "margin-left: 30px">Product reviews</h2>
		<form id="review" style ="width: 100%; display: inline-block" action= "insert.php" method="post">
		<?php
			@session_start();
			$servername = "localhost";
			$username = "root";
			$password = "";
			$dbname = "db_actionverb_autogenerated_affordance_2000_v2";

			// Create connection
			$conn =  mysqli_connect($servername, $username, $password, $dbname);

			// Check connection
			if ($conn->connect_error) {
				die("Connection failed: " . $conn->connect_error);
			} 
			#echo "Connected successfully";
			
			$sql = "SELECT a.ID,  rs.text FROM `reviewsentence_2000` as rs inner JOIN annotation as a on a.reviewsentenceID = rs.ID  where a.userID = ".$_SESSION["UID"]." and a.annotated = 0";
			$result = mysqli_query($conn, $sql) or die(mysqli_error($conn));
			
			$counter = 0;
			
			while($row = mysqli_fetch_assoc($result) and $counter < 5) {
				echo "<div class = 'sentence'>";
				echo "<div style = 'float: right; margin-left: 10px;'><b>".($row["ID"]-3)."</b></div>";	
				echo "<p id = " . $row["ID"]."  class= 'review'> ". $row["text"]."</p>";
				echo "<input type='button'  value = 'Annotate' onmousedown='getSelText()' style = 'width : 100px; height: 35px; margin-right: 25px;'>";
				echo "<br><br>";
				echo "<textarea readonly class = 'text-grey' id='a".$row["ID"]."' name = 'a".$row["ID"]."' rows='3' placeholder = 'Annotated text will appear here' form='review' style = 'width: 40%; height : 70px'></textarea>";
				echo "<textarea class = 'text' id='t".$row["ID"]."' name = 't".$row["ID"]."' rows='3' placeholder = 'Write affordance here' form='review' style = 'height : 70px'></textarea>";
				//echo "<br><br>";
				echo "<input type='button'  value = 'Clear' onmousedown='clearSelect(this)' style = 'width : 100px; height: 35px; float: none;vertical-align: middle;'>";
				echo "</div>";
				$counter += 1;
			}
		?>		
		<script language=javascript>
		var affArray = []
		function getSelText()
		{
			//get selected text
		    var txt = '';
		    if (window.getSelection)
		    {
		        txt = window.getSelection();
		    }
		    else if (document.getSelection)
		    {
		        txt = document.getSelection();
		    }
		    else if (document.selection)
		    {
		        txt = document.selection.createRange().text;
		    }
		    else return;
			ID = window.getSelection().anchorNode.parentNode.id;
			
			
			
			txt = String(txt)
			if (txt.length > 0){ 
				highlight(txt, ID)
				affArray.push([ID,txt])
				var docVal =  String(document.getElementById("a"+ID).value)
				if(docVal.length == 0){
						document.getElementById("a"+ID).value = docVal + txt 
				}
				else
					document.getElementById("a"+ID).value = docVal+"\n"+ txt
			}
			
		}
		

		
		function highlight(text, id) {
		  var inputText = document.getElementById(id);
		  var innerHTML = String(inputText.innerHTML);
		  text = String(text)
		  var index = innerHTML.indexOf(text);
		  if (index >= 0) { 
			preStr = innerHTML.substring(0,index);
			highlightText=  "<span class='highlight'>" + innerHTML.substring(index,index+text.length) + "</span>" 
			postStr = innerHTML.substring(index + text.length);
			inputText.innerHTML = preStr+highlightText+postStr;
		  }
		}
		
		function clearSelect(elem){
			var str = elem.parentNode.getElementsByTagName("p")[0].innerHTML;
			str = str.replace(/<\/?span[^>]*>/g,"");
			elem.parentNode.getElementsByTagName("p")[0].innerHTML = str;
			var areaArr = elem.parentNode.getElementsByTagName("textarea");
			for(i = 0; i <areaArr.length;i++){
				areaArr[i].value = "";
			}
		}

		
		</script>
		<br>
			<input type="submit"  value = "Submit"  style = "width : 200px; height: 70px; ">
			
			<div class= "bar-border">
				<?php 
				$sql = "SELECT count(a.ID)FROM `reviewsentence_2000` as rs inner JOIN annotation as a on a.reviewsentenceID = rs.ID  where a.userID = ".$_SESSION["UID"]." and a.annotated = 0";
				$result = mysqli_query($conn, $sql) or die(mysqli_error($conn));
				$complete  =2000 - mysqli_fetch_assoc($result)["count(a.ID)"];
				$percent = $complete / 2000 *100;
				echo "<div class = 'bar-fill' style = 'width:".$percent."%' >" ;
				if ($percent == 100){
					echo "100% complete! Thank you for your time! With gratitude, a masters student";
				}
				else if($percent >= 3){
					echo $percent."%";
				}
				?></div>
			</div>
			<label class = "progress">Progress</label>
		</form>

		<br>
		<div id = "instructions">
			<h2>Instructions</h2>
			<p style = "font-size : 110%">Click <b><a href = "Instructions.pdf" target="_blank">here</a></b> for the instructions.</p>
		</div>
	</div>
	</body>
</html>
